### ISSUE TITLE
Pokeapi wrapper

### ISSUE THREAD

**Issue by Naramsim** [togoshiorg/togoshi-bot#54]
Hi, coming from the pokeapi project.
 I see that you make raw calls to our service, instead, you could try one of our wrappers:

* https://github.com/PokeAPI/pokedex-promise-v2 if you are on a server
* https://github.com/PokeAPI/pokeapi-js-wrapper if you are on browsers

They caches requests, so they speed up your development and speed up your application

**Comment by usagi-f** [comment]
hi, @Naramsim .

We already know those libraries, but I have not used it yet.
Because, learning is one of the significance of existence of this repository.

However, it's aggressive to make better programs by making use of useful things.

thanks for the advice! 😋

---

I'm a fan of pokeapi. I support you from Japan!

**Comment by usagi-f** [comment]
@loose-art @pikoshimame and more.
Let us also use the proposed package.

**Comment by usagi-f** [comment]
Closing because there is a similar issue.

https://github.com/togoshiorg/togoshi-bot/issues/26
